store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('products/', views.AllProductView.as_view(), name='all-product'),
    path('products/category/<category_slug>/', views.category, name='category'),
    path('product/detail/<slug>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<slug>', views.add_to_cart, name='add-to-cart'),
    path('cart/remove-product/<slug>/', views.remove_from_cart, name='remove-from-cart'),
    path('cart/remove-single-product/<slug>/', views.remove_single_product_from_cart, name='remove-single-product'),
    path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('checkout/coupon/add/', views.AddCouponView.as_view(), name='add-coupon'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/order/detail/<id>/', views.order_detail, name='order-detail'),
    path('accounts/order/refund-request/<id>/', views.refund_request, name='refund-request')
]

store/forms.py
from django import forms
from django.forms import widgets


class CheckoutForm(forms.Form):

    city = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '1234 Main st'
        }
    ))
    province = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Provinsi'
        }
    ))
    address = forms.CharField(required=False, widget=forms.Textarea(
        attrs={
            'class': 'form-control',
            'placeholder': 'Jalan Tanjung Barat RT/RW 09/12'
        }
    ))

    zipcode = forms.CharField(required=False, widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': '17178'
        }
    ))
    use_default_address = forms.BooleanField(required=False)
    set_default_address = forms.BooleanField(required=False)


class CouponForm(forms.Form):
    code = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control",
                "placeholder": "Promo Code",
                "aria-label": "Recipient's username",
                "aria-describedby": "basic-addon2",
            }
        )
    )

class RefundForm(forms.Form):
    reason = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'rows': 4,
            }
        )
    )

store/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.models import User

# django views
from django.views.generic import ListView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.contrib import messages

# same app import
from .models import Product, Order, OrderItem, Address, Coupon, Customer, Refund
from .forms import CheckoutForm, CouponForm, RefundForm

from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone
from datetime import datetime

from django.utils.text import slugify


class HomeView(View):
    def get(self, *args, **kwargs):
        product_list = Product.objects.all()
        categories = Product.objects.values('category').distinct()
        search_input = self.request.GET.get('search-area')

        for category in categories:
            category['category_slug'] = slugify(category['category'])
            
        if search_input:
            products = Product.objects.filter(name__icontains=search_input)
        else:
            products = Product.objects.all()
            search_input = ''
        
        context = {
            'products': products,
            'categories': categories,
            'search_input': search_input
        }
        return render(self.request, 'store/home-page.html', context)


class AllProductView(View):
    def get(self, *args, **kwargs):
        products = Product.objects.all()
        categories = Product.objects.values('category').distinct()
        search_input = self.request.GET.get('search-area')

        for category in categories:
            category['category_slug'] = slugify(category['category'])

        if search_input:
            products = Product.objects.filter(name__icontains=search_input)
        else:
            products = Product.objects.all()
            search_input = ''
        
        context = {
            'products': products,
            'categories': categories,
            'search_input': search_input
        }
        return render(self.request, 'store/all-product.html', context)

def category(request, category_slug):
    products = Product.objects.filter(category_slug=category_slug)
    categories = Product.objects.values('category').distinct()

    for category in categories:
        category['category_slug'] = slugify(category['category'])

    search_input = request.GET.get('search-area')
    search_input = ''

    
    context = {
            'products': products,
            'categories': categories,
            'search_input': search_input
    }
    return render(request, 'store/category.html', context)

class ProductDetailView(DetailView):
    model = Product
    template_name = 'store/product-detail.html'


class CartView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(customer=self.request.user, ordered=False)
            
            return render(self.request, 'store/cart.html', {'object': order})
        except ObjectDoesNotExist:
            messages.warning(
                self.request, 'You do not have an active order for now'
            )
            return redirect('store:home')


@login_required
def add_to_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_item, created = OrderItem.objects.get_or_create(
        product=product, customer=request.user, ordered=False
    )
    order_qs = Order.objects.filter(customer=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        # check if the order item is in the order
        if order.product.filter(product__slug=product.slug).exists():
            order_item.quantity += 1
            order_item.save()
        else:
            order.product.add(order_item)
            response = HttpResponse('cart', order.product.add(order_item))
            messages.info(request, 'This item was added to your cart.')
            return redirect('store:cart')
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(customer=request.user, ordered_date=ordered_date)
        order.product.add(order_item)
        messages.info(request, 'This item was added to your cart.')
    return redirect('store:cart')


@login_required
def remove_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(customer=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        # check if the order item is in the order
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product, customer=request.user, ordered=False
            )[0]
            order.product.remove(order_item)
            messages.info(request, 'This item was removed from your cart')
            return redirect('store:cart')
        else:
            messages.info(request, 'This item was not in your cart')
            return redirect('store:cart')
    else:
        messages.info(request, 'You do not have an active order')
        return redirect('store:cart')


@login_required
def remove_single_product_from_cart(request, slug):
    product = get_object_or_404(Product, slug=slug)
    order_qs = Order.objects.filter(customer=request.user, ordered=False)

    if order_qs.exists():
        order = order_qs[0]

        # check if the item is in the order
        if order.product.filter(product__slug=product.slug).exists():
            order_item = OrderItem.objects.filter(
                product=product, customer=request.user, ordered=False
            )[0]
            if order_item.quantity > 1:
                order_item.quantity -= 1
                order_item.save()
            else:
                order.product.remove(order_item)
            messages.info(request, 'This item quantity was added')
            return redirect('store:cart')
        else:
            messages.info(request, 'This item was not in your cart')
            return redirect('store:cart')
    else:
        messages.info(request, 'You do now have an active order')
        return redirect('store:cart')


def is_valid_form(values):
    valid = True
    for field in values:
        if field == '':
            valid = False
    return valid

class CheckoutView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(customer=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'order': order,
                'couponform': CouponForm(),
                'DISPLAY_COUPON_FORM': True,
            }
            shipping_address_qs = Address.objects.filter(
                customer=self.request.user,
                default=True,
            )

            if shipping_address_qs.exists():
                context.update({
                    'default_address': shipping_address_qs[0]
                })

            return render(self.request, 'store/checkout.html', context)
        except ObjectDoesNotExist:
            return redirect('store:store')
    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)

        try:
            order = Order.objects.get(customer=self.request.user, ordered=False)

            if form.is_valid():

                # Shipping Address
                use_default_address = form.cleaned_data.get('use_default_address')
                print(use_default_address)
                if use_default_address:
                    address_qs = Address.objects.filter(
                        customer=self.request.user,
                        default=True,
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.ordered = True
                        order.save()
                    else:
                        messages.info(self.request, 'No default address available')
                        return redirect('store:checkout')
                    messages.success(self.request, 'Checkout successfull')
                    return redirect('store:home')
                else:
                    province = form.cleaned_data.get('province')
                    city = form.cleaned_data.get('city')
                    address = form.cleaned_data.get('address')
                    zipcode = form.cleaned_data.get('zipcode')

                    if is_valid_form([province, city, address, zipcode]):

                        address = Address(
                            customer=self.request.user,
                            city=city,
                            province=province,
                            address=address,
                            zipcode=zipcode,
                        )
                        

                        address.save()

                        order.shipping_address = address
                        order.ordered = True
                        order.transaction_id = datetime.now().timestamp()
                        order.save()

                        set_default_address = form.cleaned_data.get('set_default_address')
                        if set_default_address:
                            address.default = True    
                            address.save()

                        messages.success(self.request, 'Checkout Successful')
                        return redirect('store:home')
        except ObjectDoesNotExist:
           messages.warning(
               self.request, 'You do not have an active order for now'
           ) 
           return redirect('store:checkout')
            

def get_coupon(request, code):
    try:

store/templates/store/all-product.html
{% extends 'store/base.html' %}
{% load static %}

{% load humanize %}
{% load l10n %}
{% load i18n %}

{% block content %}
    {% include 'store/product_snippet.html' %}
{% endblock content %}
    

store/templates/store/base.html
<!DOCTYPE html>
{% load static %}
{% load cart_template_tags %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>DJ Ecommerce</title>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">

  <!-- Bootstrap core CSS -->
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Material Design Bootstrap -->
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  
  <!-- Your custom styles (optional) -->
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">

  <!-- own css -->
  <link rel="stylesheet" href="{% static 'css/main.css' %}">

  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>

  
  {% block navbar %}
    <!-- Navbar -->
    <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
      <div class="container">

        <!-- Brand -->
        <a class="navbar-brand waves-effect" href="{% url 'store:home' %}">
          <strong class="blue-text">DJ Ecommerce</strong>
        </a>

        <!-- Collapse -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">

          <!-- Left -->
          <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
              <a class="nav-link waves-effect" href="{% url 'store:home' %}">Home
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link waves-effect" href="{% url 'store:all-product' %}">All Product
                <span class="sr-only">(current)</span>
              </a>
            </li>
          </ul>

          <!-- Right -->
          <ul class="navbar-nav nav-flex-icons">
            <li class="nav-item">
              <a href="{% url 'store:cart' %}" class="nav-link waves-effect">
                <span class="badge red z-depth-1 mr-1">{{ request.user|cart_product_count }}</span>
                <i class="fas fa-shopping-cart"></i>
                <span class="clearfix d-none d-sm-inline-block"> Cart </span>
              </a>
            </li>
            
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'store:profile' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fas fa-user"></i>{{ request.user }}
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'account_logout' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fas fa-sign-out-alt"></i>Logout
              </a>
            </li>
            {% else %}
            <li class="nav-item">
              <a href="{% url 'store:profile' %}" class="nav-link border border-light rounded waves-effect">
                <i class="fas fa-user"></i>Login / Signup
              </a>
            </li>
            {% endif %}
              
          </ul>

        </div>

      </div>
    </nav>
    <!-- Navbar -->
  {% endblock navbar %}
  
  <div class="mt-5 pt-4">
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      {% endfor %}
    {% endif %}
  </div>
  
  {% block content %}
    
  {% endblock content %}
    
  {% block footer %}
    <!--Footer-->
    <footer class="page-footer text-center font-small mt-4 wow fadeIn">
      <hr class="my-4">

      <!-- Social icons -->
      <div class="pb-4">

        <a href="https://instagram.com/abigaelvs" target="_blank">
          <i class="fab fa-instagram mr-3"></i>
        </a>

        <a href="https://github.com/abigaelvs/" target="_blank">
          <i class="fab fa-github mr-3"></i>
        </a>
      </div>
      <!-- Social icons -->

      <!--Copyright-->
      <div class="footer-copyright py-3">
        © 2021 Copyright:
        <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> DJ Ecommerce </a>
      </div>
      <!--/.Copyright-->

    </footer>
    <!--/.Footer-->
  {% endblock footer %}
    

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>

  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>

  <!-- custom js -->
  
  {% block js %}
    
  {% endblock js %}
    

  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

store/templates/store/cart.html
{% extends 'store/base.html' %}
{% load static %}

{% load humanize %}
{% load i18n %}
{% load l10n %}

{% load cart_template_tags %}

{% block content %}
<br>
<br>
<br>
<br>

<!--Main layout-->
<main>
    <div class="container">
        <div class="table-responsive text-nowrap">
            <h2>Order Summary</h2>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">Product Name</th>
                        <th scope="col">Price</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Total Item Price</th>
                    </tr>
                </thead>
                <tbody>

                    {% for order_item in object.product.all %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ order_item.product.name }}</td>
                            {% language 'de' %}
                                <td>{{ order_item.product.price|intcomma }}</td>
                            {% endlanguage %}
                            <td>
                                <a href="{% url 'store:remove-single-product' order_item.product.slug %}">
                                    <i class="fas fa-minus mr-2"></i>
                                </a>

                                {{order_item.quantity}}

                                <a href="{% url 'store:add-to-cart' order_item.product.slug %}">
                                    <i class="fas fa-plus ml-2"></i>
                                </a>
                            </td>
                            <td>

                                {% language 'de' %}
                                    {% if order_item.product.discount_price %}
                                        <del>{{ order_item.get_total_item_price|intcomma }}</del>
                                        {{ order_item.get_total_discount_item_price|intcomma }}
                                        <span class="badge badge-primary">Saving Rp.{{ order_item.get_amount_saved|intcomma }}</span>
                                    {% else %}
                                        {{ order_item.get_total_item_price|intcomma }}
                                    {% endif %}
                                {% endlanguage %}

                                <a style="color: red; float: right;"
                                    href="{% url 'store:remove-from-cart' order_item.product.slug %}">
                                    <i class="fas fa-trash"></i>
                                </a>

                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">Your cart is empty</td>
                        </tr>
                    {% endfor %}


                    {% if object.coupon %}
                        <tr>
                            <td colspan="4">
                                <b>Coupon</b>
                            </td>
                            <td>
                                <b>
                                    {% language 'de' %}
                                    Rp. -{{ object.coupon.amount|intcomma }}
                                    {% endlanguage %}
                                </b>
                            </td>
                        </tr>
                    {% endif %}


                    {% if object.get_total %}
                        <tr>
                            <td colspan="4">
                                <b>Order Total</b>
                            </td>
                            <td>
                                <b>
                                    {% language 'de' %}
                                    {{ object.get_total|intcomma }}
                                    {% endlanguage %}
                                </b>
                            </td>
                        </tr>
                        <tr>
                            <td colspan="5">
                                <a class="btn btn-primary float-right ml-2" href="{% url 'store:checkout' %}">
                                    Proceed to Checkout
                                </a>
                                <a class="btn btn-secondary float-right" href="{% url 'store:home' %}">
                                    Continue Shopping
                                </a>
                            </td>
                        </tr>
                    {% endif %}

                </tbody>
            </table>

        </div>
    </div>
</main>
<!--Main layout-->
{% endblock content %}

store/templates/store/category.html
{% extends 'store/base.html' %}
{% load static %}

{% load humanize %}
{% load l10n %}
{% load i18n %}

{% block content %}
    {% include 'store/product_snippet.html' %}
{% endblock content %}
    

store/templates/store/product-detail.html
{% extends 'store/base.html' %}
{% load static %}
{% load humanize %}
{% load i18n %}
{% load l10n %}

{% block content %}
  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{ object.image_url }}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">Category 2</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <a href="">
                <span class="badge red mr-1">Bestseller</span>
              </a>
            </div>

            <p class="lead">
              
              {% language 'de' %}

                {% if object.discount_price %}
                  <span class="mr-1">
                    <del>Rp. {{ object.price|intcomma }}</del>
                  </span>
                  <span>Rp. {{ object.discount_price|intcomma }}</span>
                {% else %}
                  <span>Rp. {{ object.price|intcomma }}</span>
                {% endif %}

              {% endlanguage %}
                
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description|safe }}</p>

            <!-- Default input -->
            <a href="{% url 'store:add-to-cart' object.slug %}" class="btn btn-primary btn-md my-0 p" type="submit">Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>


          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}
  

store/templates/store/product_snippet.html
{% load static %}

{% load humanize %}
{% load l10n %}
{% load i18n %}

<!--Main layout-->
<main id="home">
    <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Categories:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'store:all-product' %}">All
                    <span class="sr-only">(current)</span>
                </a>
            </li>
            
            {% for category in categories %}
                <li class="nav-item">
                    <a href="{% url 'store:category' category.category_slug %}" class="nav-link">{{ category.category }}</a>
                </li>
            {% endfor %}

        </ul>
        <!-- Links -->

        <form class="form-inline" action="/" method='GET'>
            <div class="md-form my-0">
            <input class="form-control mr-sm-2" name="search-area" type="text" placeholder="Search" aria-label="Search" value="{{ search_input }}">
            </div>
        </form>
        </div>
        <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn product__container">
    
            {% for product in products %}
                <!--Grid column-->
                <div class="col-lg-3 col-md-6 mb-4 product__content {{ product.category_slug }}">

                    <!--Card-->
                    <div class="card">

                    <!--Card image-->
                    <div class="view overlay">
                        <img src="{{ product.image_url }}" class="card-img-top"
                        alt="">
                        <a href="{% url 'store:product-detail' product.slug %}">
                        <div class="mask rgba-white-slight"></div>
                        </a>
                    </div>
                    <!--Card image-->

                    <!--Card content-->
                    <div class="card-body text-center">
                        <!--Category & Title-->
                        <a href="{% url 'store:product-detail' product.slug %}" class="grey-text">
                            <h5>{{ product.category }}</h5>
                        </a>
                        <h5>
                        <strong>
                            <a href="{{ product.get_absolute_url }}" class="dark-grey-text">{{ product.name }}
                                <span class="badge badge-pill danger-color">NEW</span>
                            </a>
                        </strong>
                        </h5>

                        <a href="{% url 'store:product-detail' product.slug %}">
                            <h4 class="font-weight-bold blue-text">
                                {% language 'de' %}
                                    <strong>Rp. {{ product.price|intcomma }}</strong>
                                {% endlanguage %}
                            </h4>
                        </a>

                    </div>
                    <!--Card content-->

                    </div>
                    <!--Card-->

                </div>
                <!--Grid column-->
            {% endfor %}
                
        </div>
        <!--Grid row-->

       

    </section>
    <!--Section: Products v.3-->
    </div>
</main>
<!--Main layout-->

store/templates/store/refund_request.html
{% extends 'store/base.html' %}
{% load static %}

{% load crispy_forms_tags %}


{% block content %}
<!--Main layout-->
<main>
    <div class="container">
        <h2>Request Refund</h2>

        <form action="" method="POST">
            {% csrf_token %}
            <label for="transaction_id">Transaction ID</label>
            <input type="text" class="textinput textInput form-control" name="transaction_id" id="transaction_id" value="{{ order.transaction_id }}" disabled>
            
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
</main>
<!--Main layout-->
{% endblock content %}